### ISSUE TITLE
Logo missing from the Edgar Cayce Foundation finding aid display.

### ISSUE THREAD

**Issue by mikedurbin** [VAheritage/xtf#11]
https://search.vaheritage.org/vivaxtf/view?docId=ecf/Coll._14_20210507_150718_UTC__ead.xml;query=;brand=default

**Comment by sdm7g** [comment]
Fixed. Also added style="max-width: 600px" to fix issue with logos that haven't been resized to fit page. 
This was an obvious issue with Cayce logo, but was also a glitch with Library of Virginia and others.

**Comment by mikedurbin** [comment]
It seems only one of the finding aids actually lists a logo, and it works here: https://ead.lib.virginia.edu/vivaxtf/view?docId=ecf/Coll._2_20210622_135824_UTC__ead.xml;query=;brand=default
