### ISSUE TITLE
Update the stylesheet to address Arrangement display issues for FAs from ArchivesSpace

### ISSUE THREAD

**Issue by mtkidd** [VAheritage/xtf#4]
Submitted by: Courtney Tkacz
Sample: [https://ead.lib.virginia.edu/vivaxtf/view?docId=oai/vmfa/repositories/2/resources/200.oai_ead.xml](url)

The defined list part of the note does not have line breaks (e.g. "Series 1 Correspondence, 1822-1823, undated Series 2 Clippings, 1852")

**Comment by sdm7g** [comment]
There was no specific template for list[@type='deflist']. Added.   https://github.com/VAheritage/xtf/commit/7fdcf81d56014e3d2d8501386c734f4e3306db04
